spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yedeyang
    url: jdbc:mysql://101.132.181.196/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  freemarker:
    charset: UTF-8
    check-template-location: true
    template-loader-path: classpath:/templates

  jackson:
    default-property-inclusion: non_null
    serialization:
        write-dates-as-timestamps: true
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
server:
  servlet:
    context-path: /sell

wechat:
#  mpAppId: wx906c8298344c7927
  mpAppId: wxd898fcb01713c658
  mpAppSecret: f9f4ce494abdfb13265a73a134eab780
  mchId:
  mchKey: C5245D70627C1F8E9964D494B07350251483469312
  keyPath: D:/developer/h5.p12
  notifyUrl: http://daoyang.natapp1.cc/pay/notify
